# Change these first
owner: chatquick # Your GitHub organization or username, where this repository lives
repo: status # The name of this repository

sites:
  - name: Quicksales
    url: https://www.quicksales.vn
  - name: Quickchat
    url: https://chat.quicksales.vn


status-website:
  # Add your custom domain name, or remove the `cname` line if you don't have a domain
  # Uncomment the `baseUrl` line if you don't have a custom domain and add your repo name there
  cname: status.quicksales.vn
  # baseUrl: /your-repo-name
  logoUrl: https://raw.githubusercontent.com/upptime/upptime.js.org/master/static/img/icon.svg
  name: Monitor Website Uptime and Availability
  introTitle: "**Monitor Website Uptime and Availability**"
  introMessage: Welcome to Quicksale's real-time and historical data on system performance.
  navbar:
    - title: Status
      href: /
    - title: Facebook
      href: https://fb.com/quicksales4vn
    - title: GitHub
      href: https://github.com/$OWNER/$REPO

# Upptime also supports notifications, assigning issues, and more
# See https://upptime.js.org/docs/configuration
